- type: replace
  path: /releases/name=service-logs?
  value:
    name: service-logs
    version: latest

- type: replace
  path: /instance_groups/name=api/jobs/name=service-logs?
  value:
    name: service-logs
    release: service-logs
    properties:
      source_id: api-service-logs
      path: /var/vcap/sys/log/cloud_controller_ng/cloud_controller_ng*.log
      ca: ((loggregator_ca.certificate))
      cert: ((loggregator_tls_agent.certificate))
      key: ((loggregator_tls_agent.private_key))

- type: replace
  path: /instance_groups/name=api/jobs/name=prom_scraper?
  value:
    name: prom_scraper
    release: loggregator-agent
    consumes:
      loggregator: {from: loggregator, deployment: cf}
    properties:
      metrics:
        ca_cert: ((prom_scraper_metrics_tls.ca))
        cert: ((prom_scraper_metrics_tls.certificate))
        key: ((prom_scraper_metrics_tls.private_key))
        server_name: prom_scraper_metrics